FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# 安装 libpcap
RUN apk add --no-cache libpcap libpcap-dev netcat-openbsd

COPY backend/build/libs/*-all.jar app.jar
COPY scripts/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

EXPOSE 8080

ENTRYPOINT ["/wait-for-it.sh", "postgres:5432", "java", "-jar", "app.jar"]
