FROM alpine:3.19
RUN apk add --no-cache \
    curl \
    busybox-extras \
    bind-tools \
    netcat-openbsd \
    bash \
    lftp \
    tcpdump
COPY scripts/ /scripts/
COPY test-data/ /test-data/
RUN chmod +x /scripts/*.sh
CMD ["sleep", "infinity"]
