ARG ALPINE_IMAGE=docker.m.daocloud.io/library/alpine:3.19
FROM ${ALPINE_IMAGE}
RUN apk add --no-cache \
    curl \
    busybox-extras \
    bind-tools \
    netcat-openbsd \
    bash \
    lftp \
    tcpdump
COPY scripts/ /scripts/
COPY test-data/ /test-data/
RUN chmod +x /scripts/*.sh
CMD ["sleep", "infinity"]
